-- refresh the table
DELETE FROM Players WHERE true;
ALTER TABLE Players AUTO_INCREMENT = 1;


INSERT INTO Players (name, birthday, nationality, position, number) VALUES
                                                                        ('Kevin De Bruyne', '1991-06-28', 'Belgian', 'Midfielder', 17),
                                                                        ('Raheem Sterling', '1994-12-08', 'English', 'Forward', 7),
                                                                        ('Ruben Dias', '1997-05-14', 'Portuguese', 'Defender', 3),
                                                                        ('Ederson', '1993-08-17', 'Brazilian', 'Goalkeeper', 31),
                                                                        ('Phil Foden', '2000-05-28', 'English', 'Midfielder', 47),
                                                                        ('Mohamed Salah', '1992-06-15', 'Egyptian', 'Forward', 11),
                                                                        ('Sadio Mané', '1992-04-10', 'Senegalese', 'Forward', 10),
                                                                        ('Virgil van Dijk', '1991-07-08', 'Dutch', 'Defender', 4),
                                                                        ('Alisson Becker', '1992-10-02', 'Brazilian', 'Goalkeeper', 31),
                                                                        ('Trent Alexander-Arnold', '1998-10-07', 'English', 'Defender', 66),
                                                                        ("N'Golo Kanté", '1991-03-29', 'French', 'Midfielder', 7),
                                                                        ('Mason Mount', '1999-01-10', 'English', 'Midfielder', 19),
                                                                        ('Thiago Silva', '1984-09-22', 'Brazilian', 'Defender', 6),
                                                                        ('Edouard Mendy', '1992-03-01', 'Senegalese', 'Goalkeeper', 31),
                                                                        ('Reece James', '1999-12-08', 'English', 'Defender', 24),
                                                                        ('Bruno Fernandes', '1994-09-08', 'Portuguese', 'Midfielder', 18),
                                                                        ('Marcus Rashford', '1997-10-31', 'English', 'Forward', 10),
                                                                        ('Harry Maguire', '1993-03-05', 'English', 'Defender', 5),
                                                                        ('David de Gea', '1990-11-07', 'Spanish', 'Goalkeeper', 31),
                                                                        ('Paul Pogba', '1993-03-15', 'French', 'Midfielder', 6),
                                                                        ('Karim Benzema', '1987-12-19', 'French', 'Forward', 9),
                                                                        ('Vinícius Júnior', '2000-07-12', 'Brazilian', 'Forward', 20),
                                                                        ('Sergio Ramos', '1986-03-30', 'Spanish', 'Defender', 4),
                                                                        ('Thibaut Courtois', '1992-05-11', 'Belgian', 'Goalkeeper', 1),
                                                                        ('Luka Modrić', '1985-09-09', 'Croatian', 'Midfielder', 10),
                                                                        ('Lionel Messi', '1987-06-24', 'Argentine', 'Forward', 10),
                                                                        ('Frenkie de Jong', '1997-05-12', 'Dutch', 'Midfielder', 21),
                                                                        ('Gerard Piqué', '1987-02-02', 'Spanish', 'Defender', 3),
                                                                        ('Marc-André ter Stegen', '1992-04-30', 'German', 'Goalkeeper', 1),
                                                                        ('Ansu Fati', '2002-10-31', 'Spanish', 'Forward', 22),
                                                                        ('Luis Suárez', '1987-01-24', 'Uruguayan', 'Forward', 9),
                                                                        ('Antoine Griezmann', '1991-03-21', 'French', 'Forward', 7),
                                                                        ('Stefan Savić', '1991-01-08', 'Montenegrin', 'Defender', 15),
                                                                        ('Jan Oblak', '1993-01-07', 'Slovenian', 'Goalkeeper', 13),
                                                                        ('Koke', '1992-01-08', 'Spanish', 'Midfielder', 6),
                                                                        ('Youssef En-Nesyri', '1997-06-01', 'Moroccan', 'Forward', 15),
                                                                        ('Lucas Ocampos', '1994-07-11', 'Argentine', 'Forward', 5),
                                                                        ('Diego Carlos', '1993-03-15', 'Brazilian', 'Defender', 20),
                                                                        ('Bono', '1991-04-05', 'Moroccan', 'Goalkeeper', 13),
                                                                        ('Joan Jordán', '1994-07-06', 'Spanish', 'Midfielder', 8),
                                                                        ('Robert Lewandowski', '1988-08-21', 'Polish', 'Forward', 9),
                                                                        ('Thomas Müller', '1989-09-13', 'German', 'Forward', 25),
                                                                        ('Joshua Kimmich', '1995-02-08', 'German', 'Midfielder', 6),
                                                                        ('Manuel Neuer', '1986-03-27', 'German', 'Goalkeeper', 1),
                                                                        ('Leon Goretzka', '1995-02-06', 'German', 'Midfielder', 18),
                                                                        ('Erling Haaland', '2000-07-21', 'Norwegian', 'Forward', 9),
                                                                        ('Marco Reus', '1989-05-31', 'German', 'Forward', 11),
                                                                        ('Jude Bellingham', '2003-06-29', 'English', 'Midfielder', 22),
                                                                        ('Roman Bürki', '1990-11-14', 'Swiss', 'Goalkeeper', 1),
                                                                        ('Mats Hummels', '1988-12-16', 'German', 'Defender', 15),
                                                                        ('Emil Forsberg', '1991-10-23', 'Swedish', 'Midfielder', 10),
                                                                        ('Christopher Nkunku', '1997-11-14', 'French', 'Midfielder', 18),
                                                                        ('Ibrahima Konaté', '1999-05-25', 'French', 'Defender', 6),
                                                                        ('Péter Gulácsi', '1990-05-06', 'Hungarian', 'Goalkeeper', 1),
                                                                        ('Yussuf Poulsen', '1994-06-15', 'Danish', 'Forward', 9),
                                                                        ('Patrik Schick', '1996-01-24', 'Czech', 'Forward', 14),
                                                                        ('Moussa Diaby', '1999-07-07', 'French', 'Forward', 19),
                                                                        ('Jonathan Tah', '1996-02-11', 'German', 'Defender', 4),
                                                                        ('Lukáš Hrádecký', '1989-11-24', 'Finnish', 'Goalkeeper', 1),
                                                                        ('Florian Wirtz', '2003-05-03', 'German', 'Midfielder', 27),
                                                                        ('Cristiano Ronaldo', '1985-02-05', 'Portuguese', 'Forward', 7),
                                                                        ('Paulo Dybala', '1993-11-15', 'Argentine', 'Forward', 10),
                                                                        ('Giorgio Chiellini', '1984-08-14', 'Italian', 'Defender', 3),
                                                                        ('Wojciech Szczęsny', '1990-04-18', 'Polish', 'Goalkeeper', 1),
                                                                        ('Federico Chiesa', '1997-10-25', 'Italian', 'Forward', 22),
                                                                        ('Romelu Lukaku', '1993-05-13', 'Belgian', 'Forward', 9),
                                                                        ('Lautaro Martínez', '1997-08-22', 'Argentine', 'Forward', 10),
                                                                        ('Stefan de Vrij', '1992-02-05', 'Dutch', 'Defender', 6),
                                                                        ('Samir Handanović', '1984-07-14', 'Slovenian', 'Goalkeeper', 1),
                                                                        ('Nicolo Barella', '1997-02-07', 'Italian', 'Midfielder', 23),
                                                                        ('Zlatan Ibrahimović', '1981-10-03', 'Swedish', 'Forward', 11),
                                                                        ('Gianluigi Donnarumma', '1999-02-25', 'Italian', 'Goalkeeper', 99),
                                                                        ('Theo Hernández', '1997-10-06', 'French', 'Defender', 19),
                                                                        ('Ismaël Bennacer', '1997-12-01', 'Algerian', 'Midfielder', 4),
                                                                        ('Franck Kessié', '1996-12-19', 'Ivorian', 'Midfielder', 79),
                                                                        ('Lorenzo Insigne', '1991-06-04', 'Italian', 'Forward', 24),
                                                                        ('Kalidou Koulibaly', '1991-06-20', 'Senegalese', 'Defender', 26),
                                                                        ('Piotr Zieliński', '1994-05-20', 'Polish', 'Midfielder', 20),
                                                                        ('Alex Meret', '1997-03-22', 'Italian', 'Goalkeeper', 1),
                                                                        ('Hirving Lozano', '1995-07-30', 'Mexican', 'Forward', 11),
                                                                        ('Neymar Jr', '1992-02-05', 'Brazilian', 'Forward', 10),
                                                                        ('Kylian Mbappé', '1998-12-20', 'French', 'Forward', 7),
                                                                        ('Marquinhos', '1994-05-14', 'Brazilian', 'Defender', 5),
                                                                        ('Keylor Navas', '1986-12-15', 'Costa Rican', 'Goalkeeper', 1),
                                                                        ('Ángel Di María', '1988-02-14', 'Argentine', 'Midfielder', 11),
                                                                        ('Jonathan David', '2000-01-14', 'Canadian', 'Forward', 9),
                                                                        ('Burak Yılmaz', '1985-07-15', 'Turkish', 'Forward', 17),
                                                                        ('José Fonte', '1983-12-22', 'Portuguese', 'Defender', 6),
                                                                        ('Mike Maignan', '1995-07-03', 'French', 'Goalkeeper', 16),
                                                                        ('Renato Sanches', '1997-08-18', 'Portuguese', 'Midfielder', 18),
                                                                        ('Dimitri Payet', '1987-03-29', 'French', 'Midfielder', 10),
                                                                        ('Arkadiusz Milik', '1994-02-28', 'Polish', 'Forward', 14),
                                                                        ('Álvaro González', '1990-01-08', 'Spanish', 'Defender', 3),
                                                                        ('Steve Mandanda', '1985-03-28', 'French', 'Goalkeeper', 30),
                                                                        ('Boubacar Kamara', '1999-11-23', 'French', 'Midfielder', 4),
                                                                        ('Memphis Depay', '1994-02-13', 'Dutch', 'Forward', 10),
                                                                        ('Tino Kadewere', '1996-01-05', 'Zimbabwean', 'Forward', 11),
                                                                        ('Jason Denayer', '1995-06-28', 'Belgian', 'Defender', 5),
                                                                        ('Anthony Lopes', '1990-10-01', 'Portuguese', 'Goalkeeper', 1),
                                                                        ('Lucas Paquetá', '1997-08-27', 'Brazilian', 'Midfielder', 12),
                                                                        ('Moussa Marega', '1991-04-14', 'Malian', 'Forward', 11),
                                                                        ('Sérgio Oliveira', '1992-06-02', 'Portuguese', 'Midfielder', 27),
                                                                        ('Pepe', '1983-02-26', 'Portuguese', 'Defender', 3),
                                                                        ('Agustín Marchesín', '1988-03-16', 'Argentine', 'Goalkeeper', 1),
                                                                        ('Otávio', '1995-02-04', 'Brazilian', 'Midfielder', 25),
                                                                        ('Darwin Núñez', '1999-06-24', 'Uruguayan', 'Forward', 9),
                                                                        ('Pizzi', '1989-10-06', 'Portuguese', 'Midfielder', 21),
                                                                        ('Nicolás Otamendi', '1988-02-12', 'Argentine', 'Defender', 30),
                                                                        ('Odisseas Vlachodimos', '1994-04-26', 'Greek', 'Goalkeeper', 99),
                                                                        ('Rafa Silva', '1993-05-17', 'Portuguese', 'Midfielder', 27),
                                                                        ('Pedro Gonçalves', '1998-06-28', 'Portuguese', 'Midfielder', 28),
                                                                        ('Paulinho', '1992-11-06', 'Portuguese', 'Forward', 21),
                                                                        ('Sebastián Coates', '1990-10-07', 'Uruguayan', 'Defender', 4),
                                                                        ('Antonio Adán', '1987-05-13', 'Spanish', 'Goalkeeper', 1),
                                                                        ('Nuno Mendes', '2002-06-19', 'Portuguese', 'Defender', 5),
                                                                        ('Ricardo Horta', '1994-09-15', 'Portuguese', 'Forward', 21),
                                                                        ('Fransérgio', '1990-02-01', 'Brazilian', 'Midfielder', 30),
                                                                        ('Nicolás Gaitán', '1988-02-23', 'Argentine', 'Midfielder', 20),
                                                                        ('Matheus', '1994-03-04', 'Brazilian', 'Goalkeeper', 1),
                                                                        ('Raul Silva', '1989-11-19', 'Brazilian', 'Defender', 4),
                                                                        ('Dusan Tadic', '1988-11-20', 'Serbian', 'Forward', 10),
                                                                        ('David Neres', '1997-03-03', 'Brazilian', 'Forward', 7),
                                                                        ('Daley Blind', '1990-03-09', 'Dutch', 'Defender', 17),
                                                                        ('Andre Onana', '1996-04-02', 'Cameroonian', 'Goalkeeper', 24),
                                                                        ('Ryan Gravenberch', '2002-05-16', 'Dutch', 'Midfielder', 29),
                                                                        ('Eran Zahavi', '1987-07-25', 'Israeli', 'Forward', 7),
                                                                        ('Cody Gakpo', '1999-05-07', 'Dutch', 'Forward', 11),
                                                                        ('Olivier Boscagli', '1997-04-18', 'French', 'Defender', 18),
                                                                        ('Yvon Mvogo', '1994-06-06', 'Swiss', 'Goalkeeper', 16),
                                                                        ('Mario Götze', '1992-06-03', 'German', 'Midfielder', 19),
                                                                        ('Steven Berghuis', '1991-12-19', 'Dutch', 'Forward', 10),
                                                                        ('Bryan Linssen', '1990-10-08', 'Dutch', 'Forward', 11),
                                                                        ('Eric Botteghin', '1987-08-31', 'Brazilian', 'Defender', 33),
                                                                        ('Justin Bijlow', '1998-01-22', 'Dutch', 'Goalkeeper', 1),
                                                                        ('Orkun Kökçü', '2000-12-29', 'Turkish', 'Midfielder', 23),
                                                                        ('Teun Koopmeiners', '1998-02-28', 'Dutch', 'Midfielder', 6),
                                                                        ('Myron Boadu', '2001-01-14', 'Dutch', 'Forward', 9),
                                                                        ('Owen Wijndal', '1999-11-28', 'Dutch', 'Defender', 5),
                                                                        ('Marco Bizot', '1991-03-10', 'Dutch', 'Goalkeeper', 1),
                                                                        ('Calvin Stengs', '1998-12-18', 'Dutch', 'Forward', 23),
                                                                        ('Taison', '1988-01-13', 'Brazilian', 'Forward', 7),
                                                                        ('Marlos', '1988-06-07', 'Brazilian', 'Midfielder', 11),
                                                                        ('Davit Khocholava', '1993-10-10', 'Georgian', 'Defender', 34),
                                                                        ('Anatoliy Trubin', '2001-01-10', 'Ukrainian', 'Goalkeeper', 81),
                                                                        ('Manor Solomon', '1999-07-19', 'Israeli', 'Forward', 19),
                                                                        ('Viktor Tsyhankov', '1997-11-15', 'Ukrainian', 'Midfielder', 15),
                                                                        ('Artem Besedin', '1996-03-31', 'Ukrainian', 'Forward', 9),
                                                                        ('Oleksandr Karavayev', '1992-06-01', 'Ukrainian', 'Defender', 94),
                                                                        ('Heorhiy Bushchan', '1994-06-04', 'Ukrainian', 'Goalkeeper', 1),
                                                                        ('Mykola Shaparenko', '1998-10-04', 'Ukrainian', 'Midfielder', 10),
                                                                        ('Artem Gromov', '1997-04-12', 'Ukrainian', 'Forward', 9),
                                                                        ('Vladyslav Kochergin', '1998-03-28', 'Ukrainian', 'Midfielder', 17),
                                                                        ('Mykyta Kamenyuka', '1994-08-24', 'Ukrainian', 'Defender', 3),
                                                                        ('Mykyta Shevchenko', '1992-01-01', 'Ukrainian', 'Goalkeeper', 1),
                                                                        ('Igor Khomchenovskyi', '1996-07-11', 'Ukrainian', 'Midfielder', 10),
                                                                        ('Serhiy Buletsa', '2000-03-02', 'Ukrainian', 'Midfielder', 8),
                                                                        ('Vladyslav Supryaga', '2000-01-15', 'Ukrainian', 'Forward', 19),
                                                                        ('Yevheniy Isayenko', '1996-05-30', 'Ukrainian', 'Defender', 21),
                                                                        ('Vitaliy Mykolenko', '1999-05-29', 'Ukrainian', 'Defender', 16),
                                                                        ('Oleksandr Tkachenko', '1997-04-04', 'Ukrainian', 'Goalkeeper', 1);


INSERT INTO Leagues (name, num_teams, country) VALUES
                                                   ('Premier League', 20, 'England'),
                                                   ('La Liga', 20, 'Spain'),
                                                   ('Bundesliga', 18, 'Germany'),
                                                   ('Serie A', 20, 'Italy'),
                                                   ('Ligue 1', 20, 'France'),
                                                   ('Primeira Liga', 18, 'Portugal'),
                                                   ('Eredivisie', 18, 'Netherlands'),
                                                   ('Ukrainian Premier League', 16, 'Ukraine');

-- refresh the table
DELETE FROM teams WHERE true;
ALTER TABLE teams AUTO_INCREMENT = 1;

INSERT INTO Teams (name, city, stadium, manager, league_id) VALUES
                                                                ('Manchester City', 'Manchester', 'Etihad Stadium', 'Pep Guardiola', 1),
                                                                ('Liverpool', 'Liverpool', 'Anfield', 'Jurgen Klopp', 1),
                                                                ('Chelsea', 'London', 'Stamford Bridge', 'Thomas Tuchel', 1),
                                                                ('Manchester United', 'Manchester', 'Old Trafford', 'Ole Gunnar Solskjaer', 1),
                                                                ('Real Madrid', 'Madrid', 'Santiago Bernabeu', 'Carlo Ancelotti', 2),
                                                                ('Barcelona', 'Barcelona', 'Camp Nou', 'Xavi Hernandez', 2),
                                                                ('Atletico Madrid', 'Madrid', 'Wanda Metropolitano', 'Diego Simeone', 2),
                                                                ('Sevilla', 'Seville', 'Ramón Sánchez Pizjuán', 'Julen Lopetegui', 2),
                                                                ('Bayern Munich', 'Munich', 'Allianz Arena', 'Julian Nagelsmann', 3),
                                                                ('Borussia Dortmund', 'Dortmund', 'Signal Iduna Park', 'Marco Rose', 3),
                                                                ('RB Leipzig', 'Leipzig', 'Red Bull Arena', 'Jesse Marsch', 3),
                                                                ('Bayer Leverkusen', 'Leverkusen', 'BayArena', 'Gerardo Seoane', 3),
                                                                ('Juventus', 'Turin', 'Allianz Stadium', 'Massimiliano Allegri', 4),
                                                                ('Inter Milan', 'Milan', 'San Siro', 'Simone Inzaghi', 4),
                                                                ('AC Milan', 'Milan', 'San Siro', 'Stefano Pioli', 4),
                                                                ('Napoli', 'Naples', 'Stadio Diego Armando Maradona', 'Luciano Spalletti', 4),
                                                                ('Paris Saint-Germain', 'Paris', 'Parc des Princes', 'Mauricio Pochettino', 5),
                                                                ('Lille', 'Lille', 'Stade Pierre-Mauroy', 'Jocelyn Gourvennec', 5),
                                                                ('Marseille', 'Marseille', 'Stade Vélodrome', 'Jorge Sampaoli', 5),
                                                                ('Lyon', 'Lyon', 'Groupama Stadium', 'Peter Bosz', 5),
                                                                ('Porto', 'Porto', 'Estádio do Dragão', 'Sérgio Conceição', 6),
                                                                ('Benfica', 'Lisbon', 'Estádio da Luz', 'Jorge Jesus', 6),
                                                                ('Sporting Lisbon', 'Lisbon', 'Estádio José Alvalade', 'Rúben Amorim', 6),
                                                                ('Braga', 'Braga', 'Estádio Municipal de Braga', 'Carvalhal', 6),
                                                                ('Ajax', 'Amsterdam', 'Johan Cruyff Arena', 'Erik ten Hag', 7),
                                                                ('PSV Eindhoven', 'Eindhoven', 'Philips Stadion', 'Roger Schmidt', 7),
                                                                ('Feyenoord', 'Rotterdam', 'De Kuip', 'Arne Slot', 7),
                                                                ('AZ Alkmaar', 'Alkmaar', 'AFAS Stadion', 'Pascal Jansen', 7),
                                                                ('Shakhtar Donetsk', 'Donetsk', 'Donbass Arena', 'Roberto De Zerbi', 8),
                                                                ('Dynamo Kyiv', 'Kyiv', 'NSC Olimpiyskiy', 'Mircea Lucescu', 8),
                                                                ('Zorya Luhansk', 'Luhansk', 'Slavutych-Arena', 'Viktor Skrypnyk', 8),
                                                                ('Dnipro-1', 'Dnipro', 'Dnipro-Arena', 'Miron Markevich', 8);

INSERT INTO Team_Player (team_id, player_id) VALUES
                                                 (1, 1), (1, 2), (1, 3), (1, 4), (1, 5),
                                                 (2, 6), (2, 7), (2, 8), (2, 9), (2, 10),
                                                 (3, 11), (3, 12), (3, 13), (3, 14), (3, 15),
                                                 (4, 16), (4, 17), (4, 18), (4, 19), (4, 20),
                                                 (5, 21), (5, 22), (5, 23), (5, 24), (5, 25),
                                                 (6, 26), (6, 27), (6, 28), (6, 29), (6, 30),
                                                 (7, 31), (7, 32), (7, 33), (7, 34), (7, 35),
                                                 (8, 36), (8, 37), (8, 38), (8, 39), (8, 40),
                                                 (9, 41), (9, 42), (9, 43), (9, 44), (9, 45),
                                                 (10, 46), (10, 47), (10, 48), (10, 49), (10, 50),
                                                 (11, 51), (11, 52), (11, 53), (11, 54), (11, 55),
                                                 (12, 56), (12, 57), (12, 58), (12, 59), (12, 60),
                                                 (13, 61), (13, 62), (13, 63), (13, 64), (13, 65),
                                                 (14, 66), (14, 67), (14, 68), (14, 69), (14, 70),
                                                 (15, 71), (15, 72), (15, 73), (15, 74), (15, 75),
                                                 (16, 76), (16, 77), (16, 78), (16, 79), (16, 80),
                                                 (17, 81), (17, 82), (17, 83), (17, 84), (17, 85),
                                                 (18, 86), (18, 87), (18, 88), (18, 89), (18, 90),
                                                 (19, 91), (19, 92), (19, 93), (19, 94), (19, 95),
                                                 (20, 96), (20, 97), (20, 98), (20, 99), (20, 100),
                                                 (21, 101), (21, 102), (21, 103), (21, 104), (21, 105),
                                                 (22, 106), (22, 107), (22, 108), (22, 109), (22, 110),
                                                 (23, 111), (23, 112), (23, 113), (23, 114), (23, 115),
                                                 (24, 116), (24, 117), (24, 118), (24, 119), (24, 120),
                                                 (25, 121), (25, 122), (25, 123), (25, 124), (25, 125),
                                                 (26, 126), (26, 127), (26, 128), (26, 129), (26, 130),
                                                 (27, 131), (27, 132), (27, 133), (27, 134), (27, 135),
                                                 (28, 136), (28, 137), (28, 138), (28, 139), (28, 140),
                                                 (29, 141), (29, 142), (29, 143), (29, 144), (29, 145),
                                                 (30, 146), (30, 147), (30, 148), (30, 149), (30, 150),
                                                 (31, 151), (31, 152), (31, 153), (31, 154), (31, 155),
                                                 (32, 156), (32, 157), (32, 158), (32, 159), (32, 160);

INSERT INTO seasons (name) VALUES
                               ('2023-2024'), ('2022-2023'), ('2021-2022'), ('2020-2021');

DELETE FROM match_days WHERE true;
ALTER TABLE match_days AUTO_INCREMENT = 1;
INSERT INTO Match_days (season_id, league_id, day_number) VALUES
                                                              (1, 1, 292), (1, 1, 47), (1, 1, 317), (1, 1, 25), (1, 1, 130), (1, 1, 80), (1, 1, 198), (1, 1, 85),
                                                              (1, 2, 247), (1, 2, 175), (1, 2, 260), (1, 2, 224), (1, 2, 46), (1, 2, 116), (1, 2, 21), (1, 2, 145),
                                                              (1, 3, 42), (1, 3, 31), (1, 3, 182), (1, 3, 250), (1, 3, 116), (1, 3, 350), (1, 3, 354), (1, 3, 273),
                                                              (1, 4, 148), (1, 4, 26), (1, 4, 23), (1, 4, 260), (1, 4, 355), (1, 4, 326), (1, 4, 214), (1, 4, 189),
                                                              (1, 5, 129), (1, 5, 104), (1, 5, 139), (1, 5, 327), (1, 5, 78), (1, 5, 333), (1, 5, 326), (1, 5, 163),
                                                              (1, 6, 349), (1, 6, 62), (1, 6, 201), (1, 6, 313), (1, 6, 155), (1, 6, 137), (1, 6, 170), (1, 6, 351),
                                                              (1, 7, 201), (1, 7, 15), (1, 7, 36), (1, 7, 93), (1, 7, 356), (1, 7, 299), (1, 7, 79), (1, 7, 195),
                                                              (1, 8, 31), (1, 8, 178), (1, 8, 342), (1, 8, 32), (1, 8, 128), (1, 8, 26), (1, 8, 167), (1, 8, 245),
                                                              (2, 1, 209), (2, 1, 293), (2, 1, 252), (2, 1, 279), (2, 1, 204), (2, 1, 162), (2, 1, 166), (2, 1, 122),
                                                              (2, 2, 117), (2, 2, 119), (2, 2, 253), (2, 2, 21), (2, 2, 236), (2, 2, 274), (2, 2, 174), (2, 2, 139),
                                                              (2, 3, 269), (2, 3, 2), (2, 3, 234), (2, 3, 146), (2, 3, 153), (2, 3, 250), (2, 3, 111), (2, 3, 202),
                                                              (2, 4, 100), (2, 4, 246), (2, 4, 85), (2, 4, 83), (2, 4, 50), (2, 4, 217), (2, 4, 285), (2, 4, 64),
                                                              (2, 5, 159), (2, 5, 151), (2, 5, 317), (2, 5, 219), (2, 5, 35), (2, 5, 15), (2, 5, 79), (2, 5, 136),
                                                              (2, 6, 202), (2, 6, 3), (2, 6, 279), (2, 6, 350), (2, 6, 71), (2, 6, 314), (2, 6, 241), (2, 6, 301),
                                                              (2, 7, 316), (2, 7, 81), (2, 7, 79), (2, 7, 236), (2, 7, 333), (2, 7, 233), (2, 7, 151), (2, 7, 249),
                                                              (2, 8, 180), (2, 8, 107), (2, 8, 344), (2, 8, 197), (2, 8, 338), (2, 8, 54), (2, 8, 183), (2, 8, 304),
                                                              (3, 1, 113), (3, 1, 308), (3, 1, 359), (3, 1, 137), (3, 1, 62), (3, 1, 49), (3, 1, 4), (3, 1, 277),
                                                              (3, 2, 254), (3, 2, 21), (3, 2, 52), (3, 2, 312), (3, 2, 332), (3, 2, 348), (3, 2, 38), (3, 2, 223),
                                                              (3, 3, 21), (3, 3, 266), (3, 3, 199), (3, 3, 66), (3, 3, 170), (3, 3, 296), (3, 3, 339), (3, 3, 107),
                                                              (3, 4, 183), (3, 4, 207), (3, 4, 154), (3, 4, 305), (3, 4, 119), (3, 4, 29), (3, 4, 241), (3, 4, 127),
                                                              (3, 5, 365), (3, 5, 188), (3, 5, 287), (3, 5, 320), (3, 5, 167), (3, 5, 307), (3, 5, 41), (3, 5, 101),
                                                              (3, 6, 107), (3, 6, 241), (3, 6, 117), (3, 6, 232), (3, 6, 50), (3, 6, 233), (3, 6, 88), (3, 6, 196),
                                                              (3, 7, 243), (3, 7, 167), (3, 7, 229), (3, 7, 37), (3, 7, 301), (3, 7, 44), (3, 7, 139), (3, 7, 65),
                                                              (3, 8, 109), (3, 8, 204), (3, 8, 268), (3, 8, 189), (3, 8, 267), (3, 8, 293), (3, 8, 212), (3, 8, 269),
                                                              (4, 1, 206), (4, 1, 317), (4, 1, 297), (4, 1, 271), (4, 1, 263), (4, 1, 350), (4, 1, 89), (4, 1, 129),
                                                              (4, 2, 74), (4, 2, 93), (4, 2, 209), (4, 2, 65), (4, 2, 147), (4, 2, 357), (4, 2, 327), (4, 2, 291),
                                                              (4, 3, 57), (4, 3, 305), (4, 3, 339), (4, 3, 212), (4, 3, 329), (4, 3, 312), (4, 3, 268), (4, 3, 306),
                                                              (4, 4, 123), (4, 4, 188), (4, 4, 155), (4, 4, 255), (4, 4, 173), (4, 4, 179), (4, 4, 272), (4, 4, 276),
                                                              (4, 5, 74), (4, 5, 303), (4, 5, 232), (4, 5, 281), (4, 5, 118), (4, 5, 357), (4, 5, 131), (4, 5, 8),
                                                              (4, 6, 248), (4, 6, 183), (4, 6, 39), (4, 6, 110), (4, 6, 108), (4, 6, 142), (4, 6, 210), (4, 6, 77),
                                                              (4, 7, 149), (4, 7, 201), (4, 7, 63), (4, 7, 222), (4, 7, 94), (4, 7, 133), (4, 7, 126), (4, 7, 4),
                                                              (4, 8, 316), (4, 8, 207), (4, 8, 93), (4, 8, 264), (4, 8, 297), (4, 8, 123), (4, 8, 346), (4, 8, 79);






